#ifndef _FILE_LABEL_H_
#define _FILE_LABEL_H_

char *FILE_IO_DATA_PARSING_KEY_STRING_SAVED_DATA_START = "[DATA_save_START]";
char *FILE_IO_DATA_PARSING_KEY_STRING_SAVED_DATA_END = "[DATA_save_END]";

char *FILE_IO_DATA_PARSING_KEY_STRING_KIND_OF_DATA_START = "[Kind_Of_Data_START]";
char *FILE_IO_DATA_PARSING_KEY_STRING_KIND_OF_DATA_END = "[Kind_Of_Data_END]";

char *FILE_IO_DATA_PARSING_KEY_STRING_ARRAY_TYPE_START = "[Data_Array_Type_START]";
char *FILE_IO_DATA_PARSING_KEY_STRING_ARRAY_TYPE_END = "[Data_Array_Type_END]";

char *FILE_IO_DATA_PARSING_KEY_STRING_BIT_WIDTH_START = "[Data_Bit_Width_START]";
char *FILE_IO_DATA_PARSING_KEY_STRING_BIT_WIDTH_END = "[Data_Bit_Width_END]";

char *FILE_IO_DATA_PARSING_KEY_STRING_ROW_DATA_START = "[Row_Length_START]";
char *FILE_IO_DATA_PARSING_KEY_STRING_ROW_DATA_END = "[Row_Length_END]";

char *FILE_IO_DATA_PARSING_KEY_STRING_COL_DATA_START = "[Column_Length_START]";
char *FILE_IO_DATA_PARSING_KEY_STRING_COL_DATA_END = "[Column_Length_END]";

char *FILE_IO_DATA_PARSING_KEY_STRING_RAW_DATA_START = "[Raw_Data_START]";
char *FILE_IO_DATA_PARSING_KEY_STRING_RAW_DATA_END = "[Raw_Data_START_END]";

#endif
