#ifndef _POLY_PRIMITIVE_H_
#define _POLY_PRIMITIVE_H_

#include "poly/type.h"

#define MAXUMUM_PRIMITIVE_POLYNOMIAL_NUMBER    17

/* global variables start */
/*
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_1_INVERSE_INDEX;
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_2_INVERSE_INDEX;
//
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_4_INVERSE_INDEX;
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_8_INVERSE_INDEX;
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_16_INVERSE_INDEX;
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_32_INVERSE_INDEX;
//
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_64_INVERSE_INDEX;
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_128_INVERSE_INDEX;
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_256_INVERSE_INDEX;
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_512_INVERSE_INDEX;
//
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_1024_INVERSE_INDEX;
//extern const char_POWER_FORM *PRIMITIVE_POLYNOMIAL_2048_INVERSE_INDEX;
*/

extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_1_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_2_INVERSE_INDEX;

extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_4_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_8_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_16_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_32_INVERSE_INDEX;

extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_64_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_128_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_256_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_512_INVERSE_INDEX;

extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_1024_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_2048_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_4096_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_8192_INVERSE_INDEX;

/*
//extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_16384_INVERSE_INDEX
*/
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_16384_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_32768_INVERSE_INDEX;
extern char_POWER_FORM *PRIMITIVE_POLYNOMIAL_65536_INVERSE_INDEX;
/* global variables end */

struct struct_primitivePolynomialSet
{
    char_POWER_FORM **PRIMITIVE_POLYNOMIAL;
    unsigned int PRIMITIVE_POLYNOMIAL_NUMBER;
}typedef struct_primitivePolynomialSet;

/* global variables start */
extern struct_primitivePolynomialSet PRIMITIVE_POLYNOMIAL_SET_INVERSED;
extern struct_primitivePolynomialSet PRIMITIVE_POLYNOMIAL_SET;
/* global variables end */

void initPrimitivePolynomial(struct_primitivePolynomialSet *p);
void initPrimitivePolynomial_inversed(struct_primitivePolynomialSet *inversed, struct_primitivePolynomialSet *non_inversed);

#endif
