enum enum_FILE_IO_KIND_OF_DATA
{
    FILE_IO_KIND_OF_DATA_UNKWON,
    FILE_IO_KIND_OF_DATA_GALOIS_FIELDS,
    FILE_IO_KIND_OF_DATA_CONJUGATE_SET,
    FILE_IO_KIND_OF_DATA_SUMATION_MATRIX,
}typedef enum_FILE_IO_KIND_OF_DATA;


enum enum_FILE_IO_DATA_ARRAY_TYPE
{
    FILD_IO_DATA_ARRAY_TYPE_UNKNOWN,
    FILD_IO_DATA_ARRAY_TYPE_LINEAR,
    FILD_IO_DATA_ARRAY_TYPE_NONE_LINEAR,
}typedef enum_FILE_IO_DATA_ARRAY_TYPE;

enum enum_FILE_IO_DATA_TYPE
{
    FILE_IO_DATA_TYPE_UNKOWN,
    FILE_IO_DATA_TYPE_RAW_DATA,
    FILE_IO_DATA_TYPE_ADDRESS_OFFSET,
}typedef enum_FILE_IO_DATA_TYPE;

